package main

import (
	"fmt"
	"github.com/michael-grace/stv-voting/voting"
)

func main() {
	fmt.Println(voting.STVElection(
		2,
		[]string{"a", "b", "c"},
		[][]string{
			[]string{"a", "b"},
			[]string{"a", "b"},
			[]string{"b", "a"},
			[]string{"b", "a"},
			[]string{"b", "a"}}))

	fmt.Println(voting.STVElection(
		3,
		[]string{"Oranges", "Pears", "Chocolate", "Strawberries", "Hamburgers"},
		[][]string{
			[]string{"Oranges"},
			[]string{"Oranges"},
			[]string{"Oranges"},
			[]string{"Oranges"},
			[]string{"Pears", "Oranges"},
			[]string{"Pears", "Oranges"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Strawberries"},
			[]string{"Chocolate", "Hamburgers"},
			[]string{"Chocolate", "Hamburgers"},
			[]string{"Chocolate", "Hamburgers"},
			[]string{"Chocolate", "Hamburgers"},
			[]string{"Strawberries"},
			[]string{"Hamburgers"}}))

	fmt.Println(voting.STVElection(
		3,
		[]string{"Lynx", "Monkey", "Tarcia", "Gorilla", "Tiger"},
		[][]string{
			[]string{"Tarcia", "Gorilla"},
			[]string{"Tarcia", "Gorilla"},
			[]string{"Tarcia", "Gorilla"},
			[]string{"Tarcia", "Gorilla"},
			[]string{"Tarcia", "Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Gorilla"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Monkey"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"},
			[]string{"Lynx", "Tiger"}}))

}
